#!/bin/sh

error() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

operation=

help() {
    # TODO: check the argument is set and if so print operation specific info
    cat <<END
usage:  $0 <operation> [...]
END
}

explicit=false
list=false
owns=false

query() {
    # TODO: check mutual exclusivity of options

    if "$list"; then
        # TODO: print the files owned by the argument package
        return
    elif "$owns"; then
        # TODO: print the package that owns the argument file
        return
    else
        if "$explicit"; then
            # TODO: filter out dependencies
            :
        fi

        # TODO: loop over installed packages
    fi

    error "unimplemented operation: $operation"
}

cascade=false
recursive=false
unneeded=false

remove() {
    if [ "$#" = 0 ]; then
        return
    fi

    if "$cascade"; then
        # TODO: iterate over non-explicitly installed packages and remove them if they depend on the argument package
        :
    fi

    # TODO: remove the package

    if "$recursive"; then
        # TODO: remove dependencies of the argument package
        :
    fi

    if "$unneeded"; then
        # TODO: iterate over non-explicitly installed packages and remove them if they're not depended upon
        :
    fi

    error "unimplemented operation: $operation"
}

sysupgrade=false
refresh=false

sync() {
    if [ "$#" = 0 ]; then
        return
    fi

    if "$refresh"; then
        # TODO: git pull
        :
    fi

    if "$sysupgrade"; then
        # TODO: sync everything that's installed
        :
    fi

    # TODO: sync dependencies

    # TODO: sync the argument package

    error "unimplemented operation: $operation"
}

operate_on() {
    if [ -z "$operation" ]; then
        error 'no operation specified'
    fi

    "$operation" "$1"
}

finish_operation() {
    if [ -z "$operation" ]; then
        error 'no operation specified'
    fi

    "$operation"
}

set_operation() {
    if [ -n "$operation" ]; then
        error 'only one operation may be used at a time'
    fi

    operation="$1"
}

set_option() {
    if [ "$operation" != "$2" ]; then
        error "invalid option '-$flag'"
    fi

    eval "$1=true"
}

process_flag() {
    case "$flag" in
    c) set_option cascade remove ;;
    e) set_option explicit query ;;
    h) set_operation help ;;
    l) set_option list query ;;
    o) set_option own query ;;
    Q) set_operation query ;;
    R) set_operation remove ;;
    S) set_operation sync ;;
    s) set_option recursive remove ;;
    u)
        case "$operation" in
        remove) unneeded=true ;;
        sync) sysupgrade=true ;;
        *) error "invalid option '-$flag'" ;;
        esac
        ;;
    y) set_option refresh sync ;;
    esac
}

process_argument() {
    case "$argument" in
    --help | --query | --remove | --sync) set_operation "${argument#--}" ;;

    --explicit | --list | --owns) set_option "${argument#--}" query ;;
    --cascade | --recursive | --unneeded) set_option "${argument#--}" remove ;;
    --sysupgrade | --refresh) set_option "${argument#--}" sync ;;

    --*) error "invalid option '$argument'" ;;

    -*)
        for flag in $(printf '%s' "${argument#-}" | fold -w1); do
            process_flag
        done
        ;;
    *) operate_on "$argument" ;;
    esac
}

main() {
    for argument in "$@"; do
        process_argument
    done

    finish_operation
}

main "$@"
