#!/bin/sh

# Start of Public API

# Adds a repository.
#
# Parameters:
# - Name (only the ascii letters, hyphen, and underscore are allowed)
# - Local path (newlines not allowed currently)
# - Git url (will be cloned to the local path)
add_repository() {
    if [ $# != 0 ]; then
        echo 'error: add_repository takes 2 or 3 arguments' >&2
        return 1
    fi

    # TODO: Validate the arguments.

    printf '%s %s %s\n' "$1" "$2" "$3"
}

# End of Public API
# Anything beyond this point should not be relied upon in user configuration since it may change in a minor release.

error() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

NEWLINE='
'

operation=

help() {
    # TODO: check the argument is set and if so print operation specific info
    cat <<END
usage:  $0 <operation> [...]
END
}

explicit=false
list=false
owns=false

query() {
    if "$owns"; then
        if "$explicit"; then
            error "invalid option: '--owns' and '--explicit' may not be used together"
        fi
        if "$list"; then
            error "invalid option: '--owns' and '--list' may not be used together"
        fi

        # TODO: print the package that owns the argument file
        :
    elif "$list"; then
        if "$explicit"; then
            # TODO: filter out dependencies
            :
        fi

        if [ "$#" = 0 ]; then
            # TODO: print all files
            :
        else
            # TODO: print the files owned by the argument package
            :
        fi
    else
        if "$explicit"; then
            # TODO: filter out dependencies
            :
        fi

        # TODO: loop over installed packages
    fi

    error "unimplemented operation: $operation"
}

cascade=false
recursive=false
unneeded=false

remove() {
    if [ "$#" = 0 ]; then
        return
    fi

    if "$cascade"; then
        # TODO: iterate over non-explicitly installed packages and remove them if they depend on the argument package
        :
    fi

    # TODO: remove the package

    if "$recursive"; then
        # TODO: remove dependencies of the argument package
        :
    fi

    if "$unneeded"; then
        # TODO: iterate over non-explicitly installed packages and remove them if they're not depended upon
        :
    fi

    error "unimplemented operation: $operation"
}

sysupgrade=false
refresh=false

sync() {
    if [ "$#" = 0 ]; then
        return
    fi

    if "$refresh"; then
        # TODO: git pull
        :
    fi

    if "$sysupgrade"; then
        # TODO: sync everything that's installed
        :
    fi

    # TODO: sync dependencies

    # TODO: sync the argument package

    error "unimplemented operation: $operation"
}

operate_on() {
    if [ -z "$operation" ]; then
        error 'no operation specified'
    fi

    "$operation" "$1"
}

finish_operation() {
    if [ -z "$operation" ]; then
        error 'no operation specified'
    fi

    "$operation"
}

set_operation() {
    if [ -n "$operation" ]; then
        error 'only one operation may be used at a time'
    fi

    operation="$1"
}

set_option() {
    if [ "$operation" != "$2" ]; then
        error "invalid option '-$flag'"
    fi

    eval "$1=true"
}

process_flag() {
    case "$flag" in
    c) set_option cascade remove ;;
    e) set_option explicit query ;;
    h) set_operation help ;;
    l) set_option list query ;;
    o) set_option own query ;;
    Q) set_operation query ;;
    R) set_operation remove ;;
    S) set_operation sync ;;
    s) set_option recursive remove ;;
    u)
        case "$operation" in
        remove) unneeded=true ;;
        sync) sysupgrade=true ;;
        *) error "invalid option '-$flag'" ;;
        esac
        ;;
    y) set_option refresh sync ;;
    esac
}

process_argument() {
    case "$argument" in
    --help | --query | --remove | --sync) set_operation "${argument#--}" ;;

    --explicit | --list | --owns) set_option "${argument#--}" query ;;
    --cascade | --recursive | --unneeded) set_option "${argument#--}" remove ;;
    --sysupgrade | --refresh) set_option "${argument#--}" sync ;;

    --*) error "invalid option '$argument'" ;;

    -*)
        for flag in $(printf '%s' "${argument#-}" | fold -w1); do
            process_flag
        done
        ;;
    *) operate_on "$argument" ;;
    esac
}

# Newline separated list of space separated triples of repository name, path, and git url.
repositories=
# Newline separated list of package names.
installed_packages=
# Newline separated list of package names.
explicitly_installed_packages=

read_all_configuration() {
    for configuration_directory in '/etc' "${XDG_CONFIG_HOME-"$HOME/.config"}"; do
        read_configuration
    done
}

unset configuration_directory
unset repositories_file
unset line
read_configuration() {
    repositories_file="$configuration_directory/confman/repositories"

    if [ -e "$repositories_file" ]; then
        # shellcheck disable=SC1090
        (. "$repositories_file") |
            while IFS= read -r entry; do
                repositories="$repositories$NEWLINE$entry"
            done
    fi
}

read_all_data() {
    xdg_data_dirs="${XDG_DATA_DIRS-/usr/local/share/:/usr/share/}"

    for data_directory in \
        "${xdg_data_dirs%%:*}" \
        "${XDG_DATE_HOME-"$HOME/.local/share"}"; do
        read_data
    done
}

read_packages_file() {
    if [ -e "$1" ]; then
        # Filter out blank lines and comments.
        sed '/^\s*#/d;/^\s*$/d' <"$1"
    fi
}

unset data_directory
unset installed_packages_file
unset explicitly_installed_packages_file
read_data() {
    installed_packages_file="$data_directory/confman/installed packages"
    explicitly_installed_packages_file="$data_directory/confman/explicitly installed packages"

    installed_packages="$installed_packages$NEWLINE$(read_packages_file "$installed_packages_file")"

    explicitly_installed_packages="$explicitly_installed_packages$NEWLINE$(read_packages_file "$explicitly_installed_packages_file")"
}

main() {
    read_all_configuration
    read_all_data

    for argument in "$@"; do
        process_argument
    done

    finish_operation
}

main "$@"
